### PR TITLE
adding disconnect method to avoid locking

### PR DESCRIPTION
**Pull request by qtds35k**
Actually I'm not sure if it fixes the `too many connections` problem but it's been repeatedly passing `behave` on my computer (and `nosetests` of course). So let's just merge it into **master** and see if we can run `behave` smoothly however many times we want.

### CODE REVIEW

**Comment by tianpei2** [comment]
Yes, I with you since so far our code works even if we don't add `atexit.register(disconnect)`

**Comment by dracarys21** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/bdd5a74a-821e-4577-acb6-ec4bb7669264?env_id=ibm%3Ayp%3Aus-south "customers-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a53e9506-a90e-46c8-b92c-42a4ca964834 "customers-delivery-pipeline") deployed [customers](https://github.com/nyu-devops-fa19/customers/releases/tag/deploy-ibm-yp-us-south-vsh231-nyu.edu-dev-20191210-055217 "deploy-ibm-yp-us-south-vsh231-nyu.edu-dev-20191210-055217") to [dev](https://console.bluemix.net/apps/2b22aada-9243-4466-8271-6b1bce402384?env_id=ibm:yp:us-south "ibm:yp:us-south:vsh231@nyu.edu:dev"), including commit ba888360009d3c3e4be956a4ef5f6880526f074b

**Comment by dracarys21** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/bdd5a74a-821e-4577-acb6-ec4bb7669264?env_id=ibm%3Ayp%3Aus-south "customers-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a53e9506-a90e-46c8-b92c-42a4ca964834 "customers-delivery-pipeline") deployed [customers](https://github.com/nyu-devops-fa19/customers/releases/tag/deploy-ibm-yp-us-south-vsh231-nyu.edu-prod-20191210-225329 "deploy-ibm-yp-us-south-vsh231-nyu.edu-prod-20191210-225329") to [prod](https://console.bluemix.net/apps/b36637f6-aeeb-4daa-a1d4-71c2de28d7aa?env_id=ibm:yp:us-south "ibm:yp:us-south:vsh231@nyu.edu:prod"), including commit ba888360009d3c3e4be956a4ef5f6880526f074b

**Comment by dracarys21** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/bdd5a74a-821e-4577-acb6-ec4bb7669264?env_id=ibm%3Ayp%3Aus-south "customers-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a53e9506-a90e-46c8-b92c-42a4ca964834 "customers-delivery-pipeline") deployed [customers](https://github.com/nyu-devops-fa19/customers/releases/tag/deploy-ibm-yp-us-south-vsh231-nyu.edu-dev-20191211-161827 "deploy-ibm-yp-us-south-vsh231-nyu.edu-dev-20191211-161827") to [dev](https://console.bluemix.net/apps/2f5d855b-650e-4f91-8286-899f64aa7fbf?env_id=ibm:yp:us-south "ibm:yp:us-south:vsh231@nyu.edu:dev"), including commit ba888360009d3c3e4be956a4ef5f6880526f074b

**Comment by dracarys21** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/bdd5a74a-821e-4577-acb6-ec4bb7669264?env_id=ibm%3Ayp%3Aus-south "customers-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a53e9506-a90e-46c8-b92c-42a4ca964834 "customers-delivery-pipeline") deployed [customers](https://github.com/nyu-devops-fa19/customers/releases/tag/deploy-ibm-yp-us-south-vsh231-nyu.edu-prod-20191211-162547 "deploy-ibm-yp-us-south-vsh231-nyu.edu-prod-20191211-162547") to [prod](https://console.bluemix.net/apps/63bf6a81-3953-4b8a-afc2-d765100717d0?env_id=ibm:yp:us-south "ibm:yp:us-south:vsh231@nyu.edu:prod"), including commit ba888360009d3c3e4be956a4ef5f6880526f074b

**Pull request merged**
